#%RAML 1.0 Trait
headers:
      client_id:
        type: string
        required: true
      client_secrete:
        type: string
        required: true
      ip_address:
        type: string
        required: true
