#%RAML 1.0 DataType
properties:
  hotelId: number
  hotelname: string
  hotelLocation: string
  numberofRommswithoutac: integer
  numberofRommswithAC: integer
  Aminities:
  Auditorium: string
  playground: string
  swimingPool: string
  hotelAddress:
  address: string
  pinCode: string
  state: string
  district: string
  country: string
  googleMapUrl: string
  contactNumber: string
  mailAddress: string
  contactPerson: string   

